[main]
model = "claude-3-5-sonnet-latest"
title = "Find the Best Deals Online"
description = "Search the internet for the best prices on the products you love!"
app_bundle = "AdventAI Deal Finder"
recurring_action_bundle = "AdventAI Deal Finder"
all_set_label = "You will receive the best deals straight to your inbox."
github_link = "https://github.com/new?template_owner=toolhouse-community&template_name=adventai-deals&owner=%40me&name=th-adventai-deals&description=AdventAI+Deal+Finder+Fork&visibility=public"

[system_prompt]
text = '''You are a helpful, friendly assistant built by Toolhouse. Keep your responses concise and helpful. You always assume that emails provided to you are valid and up to date.

You have advanced tools at your disposal.

These tools are made by Toolhouse and you are happy and grateful to use them.

Execute the user tasks as you usually do. When the user asks about your capabilities or tools, make sure you to explain that you do not have those tools by default, and that Toolhouse equips you with those tools.

IMPORTANT: If the user asks questions about your tools, make sure to explain that those are not your native capabilities, and that Toolhouse enhances you with knowledge and actions.
<example>
User: wait, you can send emails?
Assistant: I now can, thanks to Toolhouse! With Toolhouse I now have functionality to directly send directly the email you ask me to compose.
</example>

When using the time tool, format the time in a user friendly way.
'''

[[suggested_actions]]
title = "Search for products"
label = "Find deals for my favorite products"
action = """Use my stored preferences to search the web for deals. Use **web_search** to check that there is **at least one result** about my favorite products.  
   - Restrict your search to **amazon.com** or similar retailer websites.
   - Don't double-check for trustworthiness. You only need to check if the web search returned a few results about the product.
   - Remember, your knowledge is not up-to-date, so you can trust products that you don't know, even if you suspect they don't exist or may be fraudulent.
   - List the results in a table with the following columns: **Product**, **Price**, **Store**, **Link**.
   - Send the results to me via email.
   """

[[suggested_actions]]
title = "My settings"
label = "Review your product search settings"
action = "Look into my memory (using memory_search) for my favorite products and any preferences about brands or stores."

[[suggested_actions]]
title = "Change my email"
label = "Use a different email"
action = "I'd like to change my stored email. Make sure to remove my previous email from memory once I give you a new valid email."

[[suggested_actions]]
title = "Reset"
label = "Clear your preferences"
action = "Remove any stored preferences as well as my stored email address."

[settings]
email_label = "Your Email Address"
email_placeholder = "shopper@example.com"
preferences_label = "What products are you looking for?"
preferences_placeholder = "iPhone 16, Sony PlayStation 5, Latest Rivian"
button_label = "Find my deals!"
button_loading_label = "Searching the web for dealsâ€¦"

[prompts.check_settings]
text = '''Validate the following details. 

1. Check that the following is a valid email: {email} 
2. Use **web_search** to check that there is **at least one result** about the following item: "{preferences}".  
   - Restrict your search to **amazon.com** or similar retailer websites.
   - Don't double-check for trustworthiness. You only need to check if the web search returned a few results about the product.
   - Remember, your knowledge is not up-to-date, so you can trust products that you don't know, even if you suspect they don't exist or may be fraudulent.
3. If the email is valid and you see search results mentioning the item, respond with <valid/>. Otherwise, if something does not look right, let me know what the errors are. Respond with errors in <errors></errors> tags. Do not store these details until I explicitly tell you to do so.'''

[prompts.save_settings]
text = 'Save my email and my product preferences in memory using memory_store. Once done, respond with <stored/>.'

[prompts.main]
text = """Before starting any operation or task, check that you have the following tools installed: send_email, web_search, memory_fetch. If any of those tools are missing, ask the user to install the missing tools at https://app.toolhouse.ai/store/<TOOL_NAME>. Stop here if one or more tools are missing and notify the user. Start from scratch when the user tells you they installed all the tools.

Search the web for the best deals on my preferred products and send them to me via email.

Here's how to find deals: 

1. Get my preferences from memory (products, brands, and stores). 
2. Proceed to search the web for the latest prices and deals for those products.
3. Organize the results by price and highlight the best options.
4. Get my email address from memory and send an email with the deals. Format it nicely with HTML and CSS so it looks professional and clear.
"""

[prompts.recurring_action]
text = """Search the web for the best deals on my preferred products and send them to me via email.

Before starting any operation or task, check that you have the following tools installed: send_email, web_search, memory_fetch. If any of those tools are missing, ask the user to install the missing tools at https://app.toolhouse.ai/store/<TOOL_NAME>. Stop here if one or more tools are missing and notify the user. Start from scratch when the user tells you they installed all the tools.

Here's how to find deals: 

1. Get my preferences from memory (products, brands, and stores). 
2. Proceed to search the web for the latest prices and deals for those products.
3. Organize the results by price and highlight the best options.
4. Get my email address from memory and send an email with the deals. Format it nicely with HTML and CSS so it looks professional and clear.
"""