[main]
model = "gpt-4o-mini"
title = "My meal planner"
description = "I will help you prepare a meal plan for the week based on your preferences."

app_bundle = "AdventAI Meal Planner"
recurring_action_bundle = "AdventAI Meal Planner Send"
all_set_label = "You will receive a new set of recipes daily in your inbox."

[system_prompt]
text = """You are a helpful, friendly assistant built by Toolhouse. Keep your responses concise and helpful. You always assume that emails provided to you are valid and up to date.

You have advanced tools at your disposal.

These tools are made by Toolhouse and you are happy and grateful to use them.

Execute the user tasks as you usually do. When the user asks about your capabilities or tools, make sure you to explain that you do not have those tools by default, and that Toolhouse equips you with those tools.

IMPORTANT: If the user asks questions about your tools, make sure to explain that those are not your native capabilities, and that Toolhouse enhances you with knowledge and actions.
<example>
User: wait, you can send emails?
Assistant: I now can, thanks to Toolhouse! With Toolhouse I now have functionality to directly send directly the email you ask me to compose.
</example>

When using the time tool, format the time in a user friendly way.
"""


[[suggested_actions]]
title = "My settings"
label = "Review your email and meal preferences"
action = "Look into my memory (using memory_search) for my meal preferences (email and dietary preferences)."

[[suggested_actions]]
title = "Change my email"
label = "Use a different email for the meal plan"
action = "I'd like to change my stored email. Make sure to remove my previous email from memory once I give you a new valid email."

[[suggested_actions]]
title = "Meal preferences"
label = "Change your dietary preferences"
action = "I'd like to change my stored dietary preferences. Make sure to remove my previous dietary preferences from memory once I give you new ones."

[[suggested_actions]]
title = "Reset"
label = "Clear your preferences"
action = "Remove my dietary preferences and my stored email address."

[settings]
email_label = "Your Email Address"
email_placeholder = "alice@example.com"
preferences_label = "Your Meal Preferences"
preferences_placeholder = "Vegetarian, rich in protein and good for marathon training"
button_label = "Create My Meal Plan"
button_loading_label = "Creating Your Meal Planâ€¦"

[prompts.check_settings]
text = '''
Validate the following details.
- Check that the following is a valid email: {email}
- Check that the following are valid meal preferences: {preferences}
  
If all look good to you, respond with <valid/>. If something does not look right, let me know what the errors are. Respond with errors in <errors></errors> tags. Do not store these details until I explicitly tell you do to so.
'''

[prompts.save_settings]
text = 'Save my email and my valid meal preferences in memory using memory_store. Once done, respond with <stored/>'

[prompts.main]
text = """
Create a meal plan (breakfast, lunch, dinner) based on my preferences for each day of the week. 
  
Before starting any operation or task, check that you have the following tools installed: current_time, send_email, memory_fetch, memory_store, memory_delete. If any of those tools are missing, ask the user to install the missing tools at https://app.toolhouse.ai/store/<TOOL_NAME>. Stop here if one or more tools are missing and notify the user. Start from scratch when the user tells you they installed all the tools.

Here's how to compile a meal plan:
  
1. Get my dietary preferences and my email from memory. If you can't find any of these preferences, ask me all the details you need before continuing. Make sure I give you meal preferences in the form of meal preferences and a validly formatted email address until you continue. Keep asking for the information you need until you have all you need. Save the details in memory.
2. Confirm whether I have any dietary restrictions, such as allergies or religious restrictions.
3. Generate a meal plan (breakfast, lunch, and dinner) that respects the my dietary restrictions and preferences. The meal plan should only have the recipe name for each one of the meals.
4. Store the meal plan in memory.
5. Email the meal plan you generated to my email. Make the email well formatted in HTML.
"""

[prompts.recurring_action]
text = """
I'd like you to create a meal plan (breakfast, lunch, dinner) based on my preferences for the current day of the week and send it to my email.
  
You have my up-to-date email and meal preferences from memory_fetch.

First, look at memory_fetch for a meal plan. If you don't have it, generate one (breakfast, lunch, and dinner). Ensure you respect my dietary restrictions and preferences. The meal plan should have a full recipe for each one of the meals. Store the plan using memory_store when done.
  
Then, send me the daily meal plan:
  
1. Get the current day of the week by calling the current_time tool.
2. Use memory_fetch to get my meal preferences and my email.
3. Email the meal plan you generated to my email. Make the email well formatted in HTML.

Assume all these information are accurate, valid, and up-to-date. Just execute these tasks without waiting for my input or confirmation.
"""