[main]
model = "gpt-4o-mini"
title = "The X Monitor"
description = "Get a daily digest of tweets from the accounts you care about."
app_bundle = "AdventAI X Monitor"
recurring_action_bundle = "AdventAI X Monitor"
all_set_label = "You will receive an X digest daily in your inbox."
github_link = "https://github.com/new?template_owner=toolhouse-community&template_name=adventai-d2&owner=%40me&name=th-adventai-d2&description=AdventAI+Day+2+Fork&visibility=public"

[system_prompt]
text = ""

[[suggested_actions]]
title = "My settings"
label = "Review your email and X accounts"
action = "Look into my memory (using memory_search) for my email address and X (formerly Twitter) accounts."

[[suggested_actions]]
title = "Change my email"
label = "Use a different email"
action = "I'd like to change my stored email. Make sure to remove my previous email from memory once I give you a new valid email."

[[suggested_actions]]
title = "Manage follow settings"
label = "Change who you’d like to see in your digest"
action = "I'd like to change my stored X (formerly Twitter) accounts I'm following. Make sure to remove my previous accounts from memory once I give you new ones."

[[suggested_actions]]
title = "Reset"
label = "Clear your preferences"
action = "Remove any X (formerly Twitter) accounts as well as my stored email address."

[settings]
email_label = "Your Email Address"
email_placeholder = "et@x.com"
preferences_label = "X Accounts You Want To Know About"
preferences_placeholder = "@toolhouseai, @aaishika, @i_am_daniele, @sunglassesface"
button_label = "Create my X digest"
button_loading_label = "Creating your X digest…"

[prompts.check_settings]
text = '''Validate the following details. 

- Check that the following is a valid email: {email} 
- Check that the following look like X accounts: {preferences} If all look good to you, respond with <valid/>. If something does not look right, let me know what the errors are. Respond with errors in <errors></errors> tags. Do not store these details until I explicitly tell you do to so.'''

[prompts.save_settings]
text = "Save my email and my X account preferences in memory using memory_store.'Save my email and my valid meal preferences in memory using memory_store. Once done, respond with <stored/>'"

[prompts.main]
text = """Compile a digest of tweets regarding the accounts I have stored in memory. 

Before starting any operation or task, check that you have the following tools installed: current_time, search_x, send_email, memory_fetch. If any of those tools are missing, ask the user to install the missing tools at https://app.toolhouse.ai/store/<TOOL_NAME>. Stop here if one or more tools are missing and notify the user. Start from scratch when the user tells you they installed all the tools.

Here's how to compile a digest: 

1. Get my preferences (X accounts I'd like to get informed about). 
2. Perform a separate search_x search for each account you find in memory. If the search does not yield results, or if you encounter an error, move to the next account. 
3. Read each tweet and add it to one of those following categories: positive coverage, negative coverage, other. Discard tweets older than 24 hours (make sure to call current_time to do that). If a section contains no tweets, make sure to say that clearly. 
4. Get my email address from memory and send an email with the tweet digest. Format it professionally with HTML and CSS as if it was coming from a prominent news organization. When putting images in the email, make sure to write <img> tags for each image URL."""

[prompts.recurring_action]
text = """I'd like you to compile a digest of tweets regarding the accounts I have stored in memory: 

1. Get my preferences (X accounts I'd like to get informed about). 
2. Perform a separate search_x search for each account you find in memory. If the search does not yield results, or if you encounter an error, move to the next account. 
3. Read each tweet and add it to one of those following categories: positive coverage, negative coverage, other. Discard tweets older than 24 hours (make sure to call current_time to do that). If a section contains no tweets, make sure to say that clearly. 
4. Get my email address from memory and send an email with the tweet digest. Format it professionally with HTML and CSS as if it was coming from a prominent news organization. When putting images in the email, make sure to write <img> tags for each image URL.

Assume all these information are accurate, valid, and up-to-date. Just execute these tasks without waiting for my input or confirmation."""